package net.cartelcraft;

import java.util.Arrays;

import net.cartelcraft.blocks.BlockTest;
import net.cartelcraft.blocks.BlockTestMulti;
import net.cartelcraft.creativetabs.CreativeTabCartelBlock;
import net.cartelcraft.creativetabs.CreativeTabCartelItem;
import net.cartelcraft.items.CartelItem;
import net.cartelcraft.items.ItemPseudoephedrine;
import net.cartelcraft.utils.CartelAPI;
import net.cartelcraft.utils.CartelAPI.ChestType;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.RenderGlobal;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.client.FMLClientHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = CartelCraft.modid, name = "Cartel Craft", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class CartelCraft {
	public static final String modid = "cartelcraft";
	public static CartelCraft instance;
	public static CartelAPI cartel;
	//Blocks
		public static Block blockTest;
		public static Block blockTestMulti;
	//Items
		public static Item itemPseudoephedrine;
	//Creative Tabs 
		public static CreativeTabs TabCartelItem = new CreativeTabCartelItem(CreativeTabs.getNextID(), "Cartel Items");
		public static CreativeTabs TabCartelBlock = new CreativeTabCartelBlock(CreativeTabs.getNextID(), "Cartel Blocks");
      
	@EventHandler
    public void preInit(FMLPreInitializationEvent event) {
		getModInfo(event.getModMetadata());
		cartel = new CartelAPI();
    }
      
	//Everything being created in your mod goes in here
    @EventHandler
    public void load(FMLInitializationEvent event) {
    	//Blocks
	    	blockTest = new BlockTest(650, Material.rock);
	    	cartel.addBlock(blockTest, "Block Test");
	    	blockTestMulti = new BlockTestMulti(651, Material.rock);
	    	cartel.addBlock(blockTestMulti, "Block Test Multi");
    	//Item
    		itemPseudoephedrine = new ItemPseudoephedrine(500);
    		cartel.addItem(itemPseudoephedrine, "Pseudoephedrine");
    		GameRegistry.addRecipe(new ItemStack(itemPseudoephedrine, 1),  new Object[] {"@@@", Character.valueOf('@'), Item.stick});
    		cartel.addSmelting(itemPseudoephedrine, 10, Block.bedrock);
    		cartel.addChestLoot(ChestType.BONUS_CHEST, itemPseudoephedrine, 10, 100);
    		cartel.addGrassSeed(itemPseudoephedrine, 5, 10);
    	
    	//GameRegistry - Game modifications(textures, adding items and blocks)
    	//LanguageRegistry - Text related modifications
    }
       
    public void getModInfo(ModMetadata meta) {
    	meta.authorList = Arrays.asList("Argixx - Lead Programmer", "BradyD - TBD", "Doug - Lead Artist");
    	meta.credits = "Mod made possible with Minecraft Forge and FML";
    	meta.logoFile = "/assets/cartelcraft/logo.png";
    	meta.autogenerated = false;
    	meta.description = "Welcome to the magical world of CartelCraft™! In CartelCraft™ you will get to live in the exciting world of illicit drug production, distribution and consumption! Want to follow in the footsteps of Walter White and create an empire, or how about getting trashed out and killing bitches in the streets of Detroit? The punk ass bitch living next door to you is producing a product better than yours, time to build a glock and fuck a punk ass bitch up! CartelCraft™, coming to distributors near you!";
    }
}